#include <furi.h>

#include <gui/gui.h>

#include <notification/notification.h>
#include <notification/notification_messages.h>

/* generated by fbt from .png files in images folder */
#include <mytestapp_icons.h>

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64

typedef enum {
    MyEventTypeKey,
    MyEventTypeDone,
} MyEventType;

typedef struct {
    MyEventType type; // The reason for this event.
    InputEvent input; // This data is specific to keypress data.
} MyEvent;

typedef struct {
    // Cursor coordinates
    int x;
    int y;

    // Timer
    int time;
    bool isRunning;
} TestAppState;

typedef struct {
    FuriMessageQueue* queue; // Event queue
    FuriTimer* timer; // Timer for redrawing the screen
    NotificationApp* notifications; // Used for controlling the backlight
    ViewPort* view_port; // Input and draw callbacks
    Gui* gui; // Fullscreen view

    TestAppState state;
} TestApp;

static void my_draw_callback(Canvas* canvas, void* context) {
    TestApp* app = (TestApp*)context;

    char str_time[11];
    itoa(app->state.time, str_time, 10);
    char str_x[11];
    itoa(app->state.x, str_x, 10);
    char str_y[11];
    itoa(app->state.y, str_y, 10);

    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 5, 30, "Ahoj!");
    canvas_draw_str(canvas, 5, 40, "T:");
    canvas_draw_str(canvas, 17, 40, str_time);
    canvas_draw_str(canvas, 5, 50, "X:");
    canvas_draw_str(canvas, 17, 50, str_x);
    canvas_draw_str(canvas, 45, 50, "Y:");
    canvas_draw_str(canvas, 57, 50, str_y);
    canvas_draw_str(canvas, app->state.x - 2, app->state.y + 8, "^");
}

static void my_input_callback(InputEvent* input_event, void* context) {
    TestApp* app = (TestApp*)context;

    if(input_event->type == InputTypeShort) {
        if(input_event->key == InputKeyLeft) app->state.x--;
        if(input_event->key == InputKeyRight) app->state.x++;
        if(input_event->key == InputKeyUp) app->state.y--;
        if(input_event->key == InputKeyDown) app->state.y++;
        if(input_event->key == InputKeyOk) app->state.isRunning = !app->state.isRunning;
        if(input_event->key == InputKeyBack) {
            MyEvent event;
            event.type = MyEventTypeDone;
            furi_message_queue_put(app->queue, &event, FuriWaitForever);
        }
    } else if (input_event->type == InputTypeLong) {
        int longDistance = 10;
        if(input_event->key == InputKeyLeft) app->state.x = app->state.x - longDistance;
        if(input_event->key == InputKeyRight) app->state.x = app->state.x + longDistance;
        if(input_event->key == InputKeyUp) app->state.y = app->state.y - longDistance;
        if(input_event->key == InputKeyDown) app->state.y = app->state.y + longDistance;
        if(input_event->key == InputKeyOk && !app->state.isRunning) app->state.time = 0;
    }

    if (app->state.x > DISPLAY_WIDTH) app->state.x = DISPLAY_WIDTH;
    if (app->state.x < 0) app->state.x = 0;
    if (app->state.y > DISPLAY_HEIGHT) app->state.y = DISPLAY_HEIGHT;
    if (app->state.y < 0) app->state.y = 0;
}

static void timer_callback(void* context) {
    TestApp* app = (TestApp*)context;

    if (app->state.isRunning) {
        app->state.time++;
    }
}

int32_t mytestapp_app(void* p) {
    UNUSED(p);

    TestApp* app = (TestApp*)malloc(sizeof(TestApp));

    app->queue = furi_message_queue_alloc(8, sizeof(MyEvent));

    app->view_port = view_port_alloc();
    view_port_draw_callback_set(app->view_port, my_draw_callback, app);
    view_port_input_callback_set(app->view_port, my_input_callback, app);
    view_port_set_orientation(app->view_port, ViewPortOrientationHorizontal);

    app->gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    app->notifications = furi_record_open(RECORD_NOTIFICATION);
    notification_message(app->notifications, &sequence_display_backlight_enforce_on);

    app->timer = furi_timer_alloc(timer_callback, FuriTimerTypePeriodic, app);
    furi_timer_start(app->timer, 1);

    app->state.x = 2;
    app->state.y = 5;
    app->state.time = 0;
    app->state.isRunning = false;

    MyEvent event;
    while(true) {
        if(furi_message_queue_get(app->queue, &event, FuriWaitForever) == FuriStatusOk) {
            if(event.type == MyEventTypeDone) {
                break;
            }
        } else {
            break;
        }
    }

    notification_message(app->notifications, &sequence_display_backlight_enforce_auto);

    furi_record_close(RECORD_NOTIFICATION);
    furi_timer_free(app->timer);
    furi_message_queue_free(app->queue);
    view_port_enabled_set(app->view_port, false);
    gui_remove_view_port(app->gui, app->view_port);
    furi_record_close(RECORD_GUI);
    view_port_free(app->view_port);

    return 0;
}
